### ISSUE TITLE
update license to reflect authorship

### ISSUE THREAD

**Issue by dr-joe-wirth** [ncezid-narst/stylo#1]
The license currently lists `2019 Lee Katz` as the copyright holder.

**Comment by kimyoungw** [comment]
i thought MIT license made it open-source?

**Comment by dr-joe-wirth** [comment]
copyright does not make something closed-source. it simply says whose intellectual property it is. In our case, it is the CDC's IP. As the stewards we can make it available under whatever conditions we desire, but the MIT license requires a copyright.

I updated the file. I forgot to flag this issue in the commit message.
